apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler

metadata:
  name: widget-server-hpa
  namespace: widget
  
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: widget-server-deployment
  minReplicas: 3
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70