apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler

metadata:
  name: widget-server-hpa
  namespace: widget

spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: widget-server-deployment
  minReplicas: 3
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 30
      policies:
        - type: Pods
          value: 2
          periodSeconds: 15
        - type: Percent
          value: 20
          periodSeconds: 30
      selectPolicy: Max # forte é a politica de Pods.
    scaleUp:
      stabilizationWindowSeconds: 30
      policies:
        - type: Percent
          value: 50
          periodSeconds: 5
